name: Publish packages

on:
  push:
    tags:
      - "v*"

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: kamod-ch/.github/.github/workflows/npm-publish-on-tag.yml@main
    with:
      pre-publish: pnpm release:check
      publish: pnpm release:publish
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
