name: Publish packages

on:
  push:
    tags:
      - "v*"

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: kamod-ch/.github/.github/actions/npm-publish-on-tag@main
        with:
          pre-publish: pnpm release:check
          publish: pnpm release:publish
          npm-token: ${{ secrets.NPM_TOKEN }}
